services:
  api:
    build:
      context: ./api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --reload --bind 0.0.0.0:8000"

    volumes:
      - ./api:/app
      - static_volume:/app/static 
      - media_volume:/app/media  
    ports:
      - "8000:8000"
    restart: unless-stopped

  

  nginx:
    image: nginx
    volumes:
      - ./front:/usr/share/nginx/html  # Just serve static files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    ports:
      - "8080:80" 
    depends_on:
      - api
  
  # not used yet
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  static_volume:
  media_volume:
