# Generated by Django 5.2.4 on 2025-08-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplice",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("base", models.BooleanField(default=False)),
                ("link_count", models.IntegerField(blank=True, default=0, null=True)),
                ("group", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstanceOf",
            fields=[
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("object_id", models.CharField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WikidataEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_link",
                    models.CharField(
                        choices=[
                            ("ownedBy", "ownedBy"),
                            ("ownerOf", "ownerOf"),
                            ("childOrgOf", "childOrgOf"),
                            ("parentOrg", "parentOrg"),
                            ("partOf", "partOf"),
                            ("hasCEO", "hasCEO"),
                            ("hasDirector", "hasDirector"),
                            ("hasChairPerson", "hasChairPerson"),
                            ("hasBoardMember", "hasBoardMember"),
                        ],
                        default="",
                        max_length=25,
                    ),
                ),
                ("object_id", models.CharField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wikidata_edges",
                        to="wikidata.accomplice",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wikidata.accomplice",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "type_of_link")},
            },
        ),
    ]
