# Generated by Django 5.2.4 on 2025-08-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wikidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='country',
            name='object_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
