# Generated by Django 5.2.4 on 2025-08-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0002_country_content_type_country_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='label',
        ),
    ]
