# Generated by Django 5.2.4 on 2025-07-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('base', models.BooleanField(default=False)),
                ('distance_to_center', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceOf',
            fields=[
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_link', models.CharField(choices=[('ownedBy', 'ownedBy'), ('ownerOf', 'ownerOf'), ('childOrgOf', 'childOrgOf'), ('parentOrg', 'parentOrg'), ('partOf', 'partOf'), ('hasCEO', 'hasCEO'), ('hasDirector', 'hasDirector'), ('hasChairPerson', 'hasChairPerson'), ('hasBoardMember', 'hasBoardMember')], default='', max_length=25)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='complicitygraph.accomplice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complicitygraph.accomplice')),
            ],
            options={
                'unique_together': {('source', 'target', 'type_of_link')},
            },
        ),
    ]
