# Generated by Django 5.2.4 on 2025-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complicitygraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplice',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
