# Generated by Django 5.2.4 on 2025-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wd_id", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "instance_of",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("distance_to_center", models.IntegerField(default=0)),
                ("radius", models.IntegerField()),
                ("colour", models.CharField(max_length=7)),
                ("group", models.IntegerField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
