# Generated by Django 5.2.4 on 2025-08-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("graph", "0001_initial"),
        ("wikidata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to="wikidata.country",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="from_accomplice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to="wikidata.accomplice",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
