# Generated by Django 5.2.4 on 2025-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
