# Generated by Django 5.2.4 on 2025-08-01 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0004_remove_graph_data_node_graph_edge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edge",
            old_name="grap",
            new_name="graph",
        ),
    ]
