# Generated by Django 5.2.4 on 2025-08-01 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0005_rename_grap_edge_graph"),
        ("wikidata", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together={("source", "target", "graph", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="graph",
            unique_together={("country", "from_accomplice")},
        ),
    ]
