# Generated by Django 5.2.4 on 2025-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0006_alter_edge_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="link_count",
            field=models.IntegerField(default=0),
        ),
    ]
