# Generated by Django 5.2.4 on 2025-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0008_alter_node_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
