# Generated by Django 5.2.4 on 2025-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_graph_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='colour',
            field=models.CharField(max_length=9),
        ),
    ]
