SELECT DISTINCT
  ?item
  ?itemLabel
  ?linkTo
  ?linkToLabel
  ?typeOfLink
  ?instanceOf
  ?instanceOfLabel
  ?country
  ?countryLabel
WHERE {
    {
      ?perpetrator wdt:P361 wd:Q134661623.
      ?perpetrator wdt:P17 ?country

    BIND("isPerpetratorWar" AS ?typeOfLink)    }
    UNION
    {
      ?perpetrator wdt:P361 wd:Q108704461.
      ?perpetrator wdt:P17 ?country

      BIND("isPerpetratorWestBank" AS ?typeOfLink)
    }

    BIND(?perpetrator AS ?item)
    BIND(?perpetrator AS ?linkTo)

  OPTIONAL { ?item wdt:P31 ?instanceOf. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,fr,es". }
}
