FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV PIP_NO_CACHE_DIR=off
ENV PIP_CACHE_DIR=/root/.cache/pip

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --cache-dir=$PIP_CACHE_DIR -r requirements.txt

COPY . .

# RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "config.wsgi:application", "--reload", "--bind", "0.0.0.0:8000"]
